export const ROUTES = {
  HOME: "/",
  EVENTOS: "/eventos",
  RANKINGS: "/rankings",
  LUCHADORES: "/luchadores",
  EQUIPOS: "/equipos",
  OPINIONES: "/opiniones",
  OPINAR: "/opinar",
  PREDICCIONES: "/predicciones",
  ADMIN: "/admin",
  ADMIN_REGISTER: "/admin/register",
  DASHBOARD: "/dashboard",
  DASHBOARD_LUCHADORES: "/dashboard/luchadores",
  DASHBOARD_EQUIPOS: "/dashboard/equipos",
  DASHBOARD_COMBATES: "/dashboard/combates",
  DASHBOARD_EVENTOS: "/dashboard/eventos",
  DASHBOARD_RANKINGS: "/dashboard/rankings",
  DASHBOARD_CATEGORIAS_PESO: "/dashboard/categorias-peso",
  DASHBOARD_MODALIDADES: "/dashboard/modalidades",
  DASHBOARD_SETTINGS: "/dashboard/settings",
  DASHBOARD_OPINIONES: "/dashboard/opiniones",
  DASHBOARD_PREDICCIONES: "/dashboard/predicciones",
  TALENTO_EXPORTADO: "/talento-exportado",
  DASHBOARD_EXPORTADOS: "/dashboard/exportados",
} as const;

