export const DEPARTAMENTOS_SALTA: string[] = [
  "Capital",
  "Anta",
  "Cachi",
  "Cafayate",
  "Cerrillos",
  "Chicoana",
  "General Güemes",
  "General José de San Martín",
  "Guachipas",
  "Iruya",
  "La Caldera",
  "La Candelaria",
  "La Poma",
  "La Viña",
  "Los Andes",
  "Metán",
  "Molinos",
  "Orán",
  "Rivadavia",
  "Rosario de la Frontera",
  "Rosario de Lerma",
  "San Carlos",
  "Santa Victoria",
];

export const UBICACIONES: Record<string, string[]> = {
  Argentina: [
    "Buenos Aires (CABA)",
    "Buenos Aires (Provincia)",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
  ],

  Bolivia: [
    "La Paz",
    "Santa Cruz de la Sierra",
    "Cochabamba",
    "Sucre",
    "Oruro",
    "Potosí",
    "Tarija",
    "Trinidad",
    "Cobija",
  ],

  Brasil: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Belém",
    "Goiânia",
    "Florianópolis",
    "Campo Grande",
    "Maceió",
    "Natal",
    "Teresina",
    "João Pessoa",
    "Aracaju",
    "Macapá",
  ],

  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Temuco",
    "Rancagua",
    "Iquique",
    "Talca",
    "Arica",
    "Puerto Montt",
    "Chillán",
    "Calama",
    "Copiapó",
    "Osorno",
    "Punta Arenas",
  ],

  Colombia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
    "Manizales",
    "Santa Marta",
    "Ibagué",
    "Pasto",
    "Villavicencio",
  ],

  Ecuador: [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Machala",
    "Durán",
    "Manta",
    "Santo Domingo",
    "Portoviejo",
    "Loja",
    "Ambato",
  ],

  Guyana: ["Georgetown", "Linden", "New Amsterdam"],

  Paraguay: [
    "Asunción",
    "Ciudad del Este",
    "San Lorenzo",
    "Luque",
    "Capiatá",
    "Lambaré",
    "Fernando de la Mora",
    "Limpio",
    "Pedro Juan Caballero",
    "Encarnación",
    "Concepción",
    "Villarrica",
  ],

  Perú: [
    "Lima",
    "Arequipa",
    "Cusco",
    "Trujillo",
    "Chiclayo",
    "Iquitos",
    "Piura",
    "Huancayo",
    "Chimbote",
    "Tacna",
    "Pucallpa",
    "Juliaca",
  ],

  Surinam: ["Paramaribo", "Lelydorp", "Nieuw Nickerie"],

  Uruguay: [
    "Montevideo",
    "Salto",
    "Ciudad de la Costa",
    "Paysandú",
    "Las Piedras",
    "Rivera",
    "Maldonado",
    "Canelones",
    "Melo",
    "Mercedes",
    "Artigas",
    "Minas",
  ],

  Venezuela: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
    "San Cristóbal",
    "Maturín",
    "Barinas",
    "Cumana",
    "Puerto La Cruz",
    "Petare",
  ],

  "Antigua y Barbuda": ["Saint John's"],
  Bahamas: ["Nassau", "Freeport"],
  Barbados: ["Bridgetown"],
  Belice: ["Belmopán", "Ciudad de Belice"],
  Cuba: ["La Habana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"],
  Dominica: ["Roseau"],
  "República Dominicana": [
    "Santo Domingo",
    "Santiago de los Caballeros",
    "San Pedro de Macorís",
    "La Romana",
    "San Francisco de Macorís",
  ],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel", "Soyapango"],
  Granada: ["Saint George's"],
  Guatemala: [
    "Ciudad de Guatemala",
    "Villa Nueva",
    "Mixco",
    "Quetzaltenango",
    "Escuintla",
  ],
  Haití: ["Puerto Príncipe", "Cap-Haïtien", "Gonaïves"],
  Honduras: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba"],
  Jamaica: ["Kingston", "Montego Bay", "Portmore", "Spanish Town"],
  México: [
    "Ciudad de México",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Toluca",
    "Tijuana",
    "León",
    "Juárez",
    "Chihuahua",
    "Hermosillo",
    "Mexicali",
    "Cancún",
    "Mérida",
    "Acapulco",
    "Veracruz",
  ],
  Nicaragua: ["Managua", "León", "Masaya", "Matagalpa"],
  Panamá: ["Ciudad de Panamá", "Colón", "David", "Santiago"],
  "San Cristóbal y Nieves": ["Basseterre"],
  "Santa Lucía": ["Castries"],
  "San Vicente y las Granadinas": ["Kingstown"],
  "Trinidad y Tobago": ["Puerto España", "San Fernando", "Chaguanas"],

  Canadá: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec",
    "Hamilton",
    "Kitchener",
  ],

  "Estados Unidos": [
    "Nueva York",
    "Los Ángeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Filadelfia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San José",
    "Austin",
    "Jacksonville",
    "Miami",
    "Atlanta",
    "Las Vegas",
    "Denver",
    "Seattle",
    "Nashville",
    "Boston",
    "Washington D.C.",
    "El Paso",
    "Minneapolis",
    "Portland",
  ],

  Albania: ["Tirana", "Durrës", "Vlorë", "Shkodër"],
  Alemania: [
    "Berlín",
    "Hamburgo",
    "Múnich",
    "Colonia",
    "Fráncfort",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Bremen",
  ],
  Andorra: ["Andorra la Vella"],
  Armenia: ["Ereván", "Gyumri", "Vanadzor"],
  Austria: ["Viena", "Graz", "Linz", "Salzburgo", "Innsbruck"],
  Azerbaiyán: ["Bakú", "Ganyá", "Sumqayıt"],
  Bélgica: ["Bruselas", "Amberes", "Gante", "Charleroi", "Lieja"],
  Bielorrusia: ["Minsk", "Gómel", "Mogilev", "Vitebsk", "Grodno"],
  "Bosnia y Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica"],
  Bulgaria: ["Sofía", "Plovdiv", "Varna", "Burgas", "Ruse"],
  Chipre: ["Nicosia", "Limassol", "Larnaca"],
  Croacia: ["Zagreb", "Split", "Rijeka", "Osijek"],
  Dinamarca: ["Copenhague", "Aarhus", "Odense", "Aalborg"],
  Eslovaquia: ["Bratislava", "Košice", "Prešov", "Žilina"],
  Eslovenia: ["Liubliana", "Maribor", "Celje", "Kranj"],
  España: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
  ],
  Estonia: ["Tallin", "Tartu", "Narva"],
  Finlandia: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Turku"],
  Francia: [
    "París",
    "Marsella",
    "Lyon",
    "Toulouse",
    "Niza",
    "Nantes",
    "Montpellier",
    "Estrasburgo",
    "Burdeos",
    "Lille",
  ],
  Georgia: ["Tiflis", "Kutaisi", "Batumi", "Rústavi"],
  Grecia: ["Atenas", "Salónica", "Patras", "Herakleion", "Larisa"],
  Hungría: ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pécs"],
  Irlanda: ["Dublín", "Cork", "Limerick", "Galway", "Waterford"],
  Islandia: ["Reikiavik", "Kópavogur", "Hafnarfjörður"],
  Italia: [
    "Roma",
    "Milán",
    "Nápoles",
    "Turín",
    "Palermo",
    "Génova",
    "Bolonia",
    "Florencia",
    "Bari",
    "Venecia",
  ],
  Kosovo: ["Pristina", "Prizren", "Peja"],
  Letonia: ["Riga", "Daugavpils", "Liepāja"],
  Liechtenstein: ["Vaduz"],
  Lituania: ["Vilna", "Kaunas", "Klaipėda", "Šiauliai"],
  Luxemburgo: ["Ciudad de Luxemburgo"],
  "Macedonia del Norte": ["Skopie", "Bitola", "Kumanovo"],
  Malta: ["La Valeta", "Birkirkara", "Mosta"],
  Moldavia: ["Chisináu", "Tiraspol", "Bălți"],
  Mónaco: ["Mónaco"],
  Montenegro: ["Podgorica", "Nikšić", "Bijelo Polje"],
  Noruega: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø"],
  "Países Bajos": [
    "Ámsterdam",
    "Róterdam",
    "La Haya",
    "Utrecht",
    "Eindhoven",
    "Groninga",
  ],
  Polonia: [
    "Varsovia",
    "Cracovia",
    "Lodz",
    "Breslavia",
    "Poznań",
    "Gdansk",
    "Szczecin",
    "Katowice",
  ],
  Portugal: ["Lisboa", "Oporto", "Braga", "Coímbra", "Aveiro", "Faro"],
  "Reino Unido": [
    "Londres",
    "Birmingham",
    "Manchester",
    "Leeds",
    "Glasgow",
    "Edimburgo",
    "Sheffield",
    "Bradford",
    "Liverpool",
    "Bristol",
    "Cardiff",
    "Belfast",
  ],
  "República Checa": ["Praga", "Brno", "Ostrava", "Pilsen"],
  Rumania: ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanza"],
  Rusia: [
    "Moscú",
    "San Petersburgo",
    "Novosibirsk",
    "Ekaterimburgo",
    "Kazán",
    "Nizhni Nóvgorod",
    "Cheliábinsk",
    "Samara",
    "Omsk",
    "Rostov del Don",
    "Ufá",
    "Krasnoyarsk",
    "Perm",
    "Voronezh",
    "Volgogrado",
  ],
  "San Marino": ["San Marino"],
  Serbia: ["Belgrado", "Novi Sad", "Niš", "Kragujevac"],
  Suecia: ["Estocolmo", "Gotemburgo", "Malmö", "Uppsala", "Västerås"],
  Suiza: ["Zúrich", "Ginebra", "Basilea", "Berna", "Lausana"],
  Turquía: [
    "Estambul",
    "Ankara",
    "Esmirna",
    "Bursa",
    "Adana",
    "Gaziantep",
    "Konya",
    "Antalya",
    "Kayseri",
    "Mersin",
  ],
  Ucrania: [
    "Kiev",
    "Járkov",
    "Odesa",
    "Dnipro",
    "Donetsk",
    "Zaporizhzhia",
    "Lviv",
    "Mariúpol",
    "Mykolaiv",
    "Lugansk",
  ],
  "Ciudad del Vaticano": ["Ciudad del Vaticano"],

  Afganistán: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  "Arabia Saudí": [
    "Riad",
    "Yeda",
    "La Meca",
    "Medina",
    "Dammam",
    "Taif",
    "Buraidah",
  ],
  Baréin: ["Manama", "Rifaa", "Al Muharraq"],
  Bangladés: ["Daca", "Chittagong", "Sylhet", "Rajshahi", "Khulna"],
  Brunéi: ["Bandar Seri Begawan"],
  Bután: ["Timbu", "Phuntsholing"],
  Camboya: ["Nom Pen", "Siem Riep", "Battambang"],
  China: [
    "Pekín",
    "Shanghái",
    "Guangzhou",
    "Shenzhen",
    "Chongqing",
    "Tianjin",
    "Wuhan",
    "Chengdu",
    "Hangzhou",
    "Xi'an",
    "Nanjing",
    "Harbin",
    "Shenyang",
    "Qingdao",
    "Jinan",
  ],
  "Corea del Norte": ["Pyongyang", "Hamhung", "Chongjin"],
  "Corea del Sur": [
    "Seúl",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
  ],
  "Emiratos Árabes Unidos": [
    "Dubai",
    "Abu Dabi",
    "Sharjah",
    "Ajmán",
    "Ras al-Jaima",
  ],
  Filipinas: [
    "Manila",
    "Quezon City",
    "Davao",
    "Caloocan",
    "Cebu",
    "Zamboanga",
    "Antipolo",
  ],
  India: [
    "Bombay",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmadabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Visakhapatnam",
    "Indore",
  ],
  Indonesia: [
    "Yakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Bekasi",
    "Makassar",
    "Depok",
    "Semarang",
    "Palembang",
    "Tangerang",
  ],
  Irak: ["Bagdad", "Basora", "Mosul", "Erbil", "Sulaymaniyah"],
  Irán: [
    "Teherán",
    "Mascad",
    "Isfahán",
    "Tabriz",
    "Karaj",
    "Shiraz",
    "Ahvaz",
    "Qom",
  ],
  Israel: ["Jerusalén", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
  Japón: [
    "Tokio",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Kobe",
    "Kyoto",
    "Fukuoka",
    "Kawasaki",
    "Saitama",
  ],
  Jordania: ["Ammán", "Zarqa", "Irbid", "Rusaifa"],
  Kazajistán: [
    "Almatý",
    "Nursultán",
    "Shymkent",
    "Aktobé",
    "Taraz",
    "Pavlodar",
  ],
  Kirguistán: ["Biskek", "Osh", "Jalal-Abad"],
  Kuwait: ["Kuwait City", "Hawalli", "Salmiya"],
  Laos: ["Vientián", "Savannakhet", "Pakse"],
  Líbano: ["Beirut", "Trípoli", "Sidón", "Tiro"],
  Malasia: [
    "Kuala Lumpur",
    "Subang Jaya",
    "George Town",
    "Johor Bahru",
    "Ipoh",
    "Kota Kinabalu",
  ],
  Maldivas: ["Malé"],
  Mongolia: ["Ulán Bator", "Erdenet", "Darkhan"],
  Myanmar: ["Naipyidó", "Rangún", "Mandalay", "Bago"],
  Nepal: ["Katmandú", "Pokhara", "Biratnagar", "Birgunj"],
  Omán: ["Mascate", "Seeb", "Salalah", "Bawshar"],
  Pakistán: [
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Islamabad",
    "Gujranwala",
    "Multan",
    "Peshawar",
    "Quetta",
  ],
  Palestina: ["Ramallah", "Gaza", "Hebrón", "Nablus"],
  Catar: ["Doha", "Al Rayyan", "Al Wakrah"],
  Singapur: ["Singapur"],
  Siria: ["Damasco", "Alepo", "Homs", "Latakia", "Hama"],
  "Sri Lanka": ["Colombo", "Dehiwala", "Moratuwa", "Kandy"],
  Taiwán: ["Taipéi", "Kaohsiung", "Taichung", "Tainan"],
  Tayikistán: ["Dusambé", "Juyand", "Juyán"],
  Tailandia: [
    "Bangkok",
    "Nonthaburi",
    "Pak Kret",
    "Hat Yai",
    "Chiang Mai",
    "Pattaya",
  ],
  Turkmenistán: ["Asjabad", "Türkmenabat", "Daşoguz"],
  Uzbekistán: [
    "Taskent",
    "Namangan",
    "Samarcanda",
    "Andiyán",
    "Nukus",
    "Bujarà",
  ],
  Vietnam: [
    "Ho Chi Minh",
    "Hanói",
    "Da Nang",
    "Haiphong",
    "Biên Hòa",
    "Cần Thơ",
  ],
  Yemen: ["Saná", "Adén", "Taiz", "Al Hudaydah", "Ibb"],

  Argelia: ["Argel", "Orán", "Constantina", "Annaba", "Blida"],
  Angola: ["Luanda", "Huambo", "Lobito", "Benguela", "Malanje"],
  Benín: ["Cotonú", "Abomey-Calavi", "Parakou", "Lomé"],
  Botsuana: ["Gaborone", "Francistown", "Maun"],
  "Burkina Faso": ["Uagadugú", "Bobo Dioulasso", "Koudougou"],
  Burundi: ["Buyumbura", "Muyinga", "Gitega"],
  "Cabo Verde": ["Praia", "Mindelo"],
  Camerún: ["Yaundé", "Duala", "Bamenda", "Bafoussam"],
  Chad: ["Yamena", "Moundou", "Sarh"],
  Comoras: ["Moroni"],
  "República del Congo": ["Brazzaville", "Pointe-Noire", "Lubumbashi"],
  "República Democrática del Congo": [
    "Kinshasa",
    "Lubumbashi",
    "Mbuji-Mayi",
    "Kananga",
    "Kisangani",
  ],
  "Costa de Marfil": ["Abiyán", "Bouaké", "Daloa", "San Pédro", "Yamoussoukro"],
  Yibuti: ["Yibuti"],
  Egipto: ["El Cairo", "Alejandría", "Giza", "Shubra el-Jaima", "Puerto Saíd"],
  Eritrea: ["Asmara", "Keren", "Masawa"],
  Etiopía: ["Addis Abeba", "Gondar", "Dire Daua", "Mekele", "Adama", "Hawasa"],
  Gabón: ["Libreville", "Port-Gentil", "Franceville"],
  Gambia: ["Banjul", "Serekunda", "Brikama"],
  Ghana: ["Acra", "Kumasi", "Tamale", "Sekondi-Takoradi"],
  Guinea: ["Conakri", "Nzérékoré", "Kindia"],
  "Guinea-Bisáu": ["Bisáu"],
  "Guinea Ecuatorial": ["Malabo", "Bata"],
  Kenia: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  Lesoto: ["Maseru", "Teyateyaneng", "Mafeteng"],
  Liberia: ["Monrovia", "Gbarnga", "Buchanan"],
  Libia: ["Trípoli", "Bengasi", "Misrata", "Tobruk"],
  Madagascar: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa"],
  Malaui: ["Lilongüe", "Blantire", "Mzuzu"],
  Malí: ["Bamako", "Sikasso", "Mopti", "Koutiala"],
  Marruecos: [
    "Casablanca",
    "Fez",
    "Marrakech",
    "Tánger",
    "Rabat",
    "Salé",
    "Agadir",
    "Meknes",
  ],
  Mauritania: ["Nuakchot", "Nuadibú"],
  Mauricio: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix"],
  Mozambique: ["Maputo", "Matola", "Beira", "Nampula"],
  Namibia: ["Windhoek", "Rundu", "Walvis Bay", "Oshakati"],
  Níger: ["Niamey", "Zinder", "Maradi"],
  Nigeria: [
    "Lagos",
    "Kano",
    "Ibadán",
    "Kaduna",
    "Port Harcourt",
    "Benin City",
    "Maiduguri",
    "Zaria",
    "Abuja",
    "Aba",
  ],
  Ruanda: ["Kigali", "Butare", "Gitarama"],
  "Santo Tomé y Príncipe": ["Santo Tomé"],
  Senegal: ["Dakar", "Pikine", "Touba", "Thiès", "Saint-Louis"],
  Seychelles: ["Victoria"],
  "Sierra Leona": ["Freetown", "Bo", "Kenema"],
  Somalia: ["Mogadiscio", "Hargeisa", "Berbera", "Kismayo"],
  Sudáfrica: [
    "Johannesburgo",
    "Ciudad del Cabo",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Pietermaritzburg",
    "Germiston",
  ],
  Sudán: ["Jartum", "Omdurmán", "Port Sudán", "Kassala"],
  "Sudán del Sur": ["Yuba", "Malakal", "Wau"],
  Suazilandia: ["Mbabane", "Manzini", "Lobamba"],
  Tanzania: ["Dodoma", "Dar es Salaam", "Mwanza", "Arusha", "Zanzibar"],
  Togo: ["Lomé", "Sokodé", "Kpalimé"],
  Túnez: ["Túnez", "Sfax", "Susa", "Bizerta"],
  Uganda: ["Kampala", "Gulu", "Mbarara", "Jinja"],
  Zambia: ["Lusaka", "Ndola", "Kitwe", "Kabwe"],
  Zimbabue: ["Harare", "Bulawayo", "Chitungwiza", "Mutare"],

  Australia: [
    "Sídney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaida",
    "Canberra",
    "Gold Coast",
    "Newcastle",
    "Wollongong",
    "Darwin",
    "Hobart",
  ],
  Fiyi: ["Suva", "Lautoka", "Nadi"],
  Kiribati: ["Tarawa del Sur"],
  "Islas Marshall": ["Majuro"],
  Micronesia: ["Palikir"],
  Nauru: ["Yaren"],
  "Nueva Zelanda": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
  ],
  Palaos: ["Ngerulmud"],
  "Papúa Nueva Guinea": ["Port Moresby", "Lae", "Mount Hagen"],
  Samoa: ["Apia"],
  "Islas Salomón": ["Honiara"],
  Tonga: ["Nukualofa"],
  Tuvalu: ["Funafuti"],
  Vanuatu: ["Port Vila"],
};

export const PAISES: string[] = [
  "Argentina",
  ...Object.keys(UBICACIONES)
    .filter((p) => p !== "Argentina")
    .sort((a, b) => a.localeCompare(b, "es")),
];

export function getCiudadesDePais(pais: string): string[] {
  return UBICACIONES[pais] ?? [];
}

export function parsearUbicacion(ciudadDB: string): {
  ciudad: string;
  departamento: string;
} {
  const PREFIJO = "Salta - ";
  if (ciudadDB.startsWith(PREFIJO)) {
    return {
      ciudad: "Salta",
      departamento: ciudadDB.slice(PREFIJO.length),
    };
  }
  return { ciudad: ciudadDB, departamento: "" };
}

export function construirValorCiudad(
  ciudad: string,
  departamento?: string,
): string {
  if (ciudad === "Salta" && departamento) {
    return `Salta - ${departamento}`;
  }
  return ciudad;
}
